aliyun:
    oss:
        bucketName: spring-boot-case-tlias
        endpoint: https://oss-cn-hangzhou.aliyuncs.com
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Zzc20031202
        url: jdbc:mysql://localhost:3306/tlias
        username: root
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 1000MB
logging:
    level:
        org.springframework.jdbc.support.JdbcTransactionManager: debug