sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Zzc20031202

  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: spring-boot-cangqiong

  redis:
    host: localhost
    port: 6379
    password: Zzc20031202
    database: 0